apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      env:
        - name: HOST_DB
          value: "svc-db-noticias:3306"
        - name: USER_DB
          value: "root"
        - name: PASS_DB
          value: "q1w2e3r4"
        - name: DATABASE_DB
          value: "empresa"
